In [25]:
# borrowed from:
# https://github.com/zalandoresearch/fashion-mnist

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import subprocess
from datetime import datetime
from threading import Thread, Event

def get_sprite_image(to_visualise, do_invert=True):
    to_visualise = vector_to_matrix_mnist(to_visualise)
    if do_invert:
        to_visualise = invert_grayscale(to_visualise)
    return create_sprite_image(to_visualise)

def vector_to_matrix_mnist(mnist_digits):
    import numpy as np
    """Reshapes normal mnist digit (batch,28*28) to matrix (batch,28,28)"""
    return np.reshape(mnist_digits, (-1, 28, 28))

def invert_grayscale(mnist_digits):
    """ Makes black white, and white black """
    return 255 - mnist_digits

def create_sprite_image(images):
    import numpy as np
    """Returns a sprite image consisting of images passed as argument. Images should be count x width x height"""
    if isinstance(images, list):
        images = np.array(images)
    img_h = images.shape[1]
    img_w = images.shape[2]
    n_plots = int(np.ceil(np.sqrt(images.shape[0])))

    spriteimage = np.ones((img_h * n_plots, img_w * n_plots))

    for i in range(n_plots):
        for j in range(n_plots):
            this_filter = i * n_plots + j
            if this_filter < images.shape[0]:
                this_img = images[this_filter]
                spriteimage[i * img_h:(i + 1) * img_h,
                j * img_w:(j + 1) * img_w] = this_img

    return spriteimage

def load_mnist(path, kind='train'):
    import os
    import gzip
    import numpy as np

    """Load MNIST data from `path`"""
    labels_path = os.path.join(path,
                               '%s-labels-idx1-ubyte.gz'
                               % kind)
    images_path = os.path.join(path,
                               '%s-images-idx3-ubyte.gz'
                               % kind)

    with gzip.open(labels_path, 'rb') as lbpath:
        labels = np.frombuffer(lbpath.read(), dtype=np.uint8,
                               offset=8)

    with gzip.open(images_path, 'rb') as imgpath:
        images = np.frombuffer(imgpath.read(), dtype=np.uint8,
                               offset=16).reshape(len(labels), 784)

    return images, labels

filePath = 'C:/Users/dvjr2/Google Drive/Documents/Syracuse/IST_718_BigDataAnalytics/Labs/Lab_003'

In [2]:
X, Y = load_mnist(path=filePath, kind='t10k')

In [3]:
type(X)

numpy.ndarray

In [4]:
X # each array is the grid that creates a digit

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [6]:
type(Y) # the number each array represents

numpy.ndarray

In [7]:
Y

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
len(X)

10000

In [9]:
len(Y)

10000

In [11]:
X[123] # 

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0, 216, 254,  26,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  25, 155, 253, 116,   1,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   6, 216, 254, 254,  17,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 136, 254, 238,
        62,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  7

In [15]:
Y[123]

6

In [16]:
len(X[2])

784

In [31]:
test = pd.DataFrame(list(map(np.ravel, X)))

In [35]:
test['Number'] =  Y

In [36]:
test

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  \
0     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
1     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
2     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
3     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
4     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
5     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
6     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
7     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
8     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9     0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
10    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
11    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
12    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
13    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
14    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
15    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
16    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
17    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
18    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
19    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
20    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
21    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
22    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
23    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
24    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
25    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
26    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
27    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
28    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
29    0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
...  .. .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...   
9970  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9971  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9972  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9973  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9974  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9975  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9976  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9977  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9978  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9979  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9980  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9981  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9982  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9983  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9984  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9985  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9986  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9987  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9988  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0   
9989  0  0  0  0  0  0  0  0

In [38]:
test.to_csv('formatted_number_data_test.csv', index = False)

In [39]:
# with train data
X, Y = load_mnist(path=filePath)
test = pd.DataFrame(list(map(np.ravel, X)))
test['Number'] =  Y
test.to_csv('formatted_number_data_train.csv', index = False)